export enum MutationTypes {
  SAMPLE_MUTATION = "SAMPLE_MUTATION",
  SAMPLE_MUTATION_FULFILLED = "SAMPLE_MUTATION_FULFILLED",
  SAMPLE_MUTATION_FAILD = "SAMPLE_MUTATION_FAILD",

}

export default MutationTypes;
