export const MutationTypes = {
  FETCH_HOUSE_DETAILS: "FETCH_HOUSE_DETAILS",
  FETCH_HOUSE_DETAILS_FULFILLED: "FETCH_HOUSE_DETAILS_FULFILLED",
  FETCH_HOUSE_DETAILS_FAILD: "FETCH_HOUSE_DETAILS_FAILD",
};

export default MutationTypes;
